### PR TITLE
fix api routes to `api/products/*` closes #20

### LINKED ISSUE #20: fix `/api` routes in `server.js` to use `routes/index.js` to complete `api/product` route
the current routes/index.js isn't being used as expected (being used as session route); remove session routing and replace with routes to the various routes in their modules.
```javascript
//routes/index.js
router.use('/products', require('./productRoutes'));
router.use('/orders', require('./orderRoutes'));
router.use('/sessions', require('./sessionRoutes'));
```
```javascript
//routes/productRoutes.js
router.get('/:productId', (req, res, next) => {...})
```

### PR DESCRIPTION
**Pull request by o6nH**
`server/index.js` includes `/api` route
`routes/index.js` includes `/products` route
`routes/productRoutes.js` includes `/:productId` route

### CODE REVIEW

File: server/routes/productRoutes.js [hunk 1]
```diff
@@ -1,52 +1,49 @@
...
+                }
+            }))
+        } catch (err) {
+            console.error(err);
         }
-        const product = await Product.update( uProd, {
-            where: {
-                id: req.params.id
+    })
+    .put(async (req, res, next) => {
```
Comment (katherinepeterson) [inline server/routes/productRoutes.js]: I feel like this route could be simplified to just use req.body instead of uProd
